// <auto-generated />
namespace Proyecto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class ActualizacionCotizador1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ActualizacionCotizador1));
        
        string IMigrationMetadata.Id
        {
            get { return "202608140439384_ActualizacionCotizador1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
